### ISSUE TITLE
Is any hyperparameter change required to achieve the paper results for ReID?

### ISSUE THREAD

**Issue by pratikm141** [KovenYu/state-information#1]
I ran the code as it is and I got the following results:
market 
**Train**  loss_surrogate 0.177   loss_align 0.012   loss_total 0.302 
**Test**  r1 71.467   r5 85.303   r10 89.222   MAP 44.665 

duke
**Train**  loss_surrogate 0.151   loss_align 0.022   loss_total 0.368 
**Test**  r1 72.621   r5 82.451   r10 85.862   MAP 53.036 

Do I need to change any hyperparameter to achieve the paper results?
Also can you provide a link to you trained models.

**Comment by KovenYu** [comment]
Thanks for your attention. 

No. The hypers are defined in args.yaml. I checked the code before uploading.. so I also have no idea what happened in your case.

Your numbers on Duke match the ones I got. But on Market it seems abnormally lower.. Could you run for a second time with less epoch, say 30? It returns out that unsupervised learning can be unstable sometimes. Sometimes it may overfit. Looking forward to your feedback!

Trained models can be found [here](https://mega.nz/#F!eI90mQaR!zol1E4Q5OX7i0yFLEVvNLQ). But these are a bit different from the ones used to report numbers in the paper. The market one is a bit higher and duke one a bit lower. To use these trained models, simply replace the pretrain_path in args.yaml as well as setting epoch to 0.

**Comment by pratikm141** [comment]
Thanks for responding.
Can you please provide google drive links for the trained models. It will be easier for me to download.

**Comment by KovenYu** [comment]
sorry I had ran out of my google drive space as a free user LOL. MEGA is also very easy to use. It won't cost you much time.

**Comment by pratikm141** [comment]
ok.. thanks :)
