### ISSUE TITLE
Question about :"views = self.view_memory[idx.nonzero().squeeze(dim=1).numpy()]"

### ISSUE THREAD

**Issue by Zhen-ao** [KovenYu/state-information#2]
I tried to run the code, but I got an error at line 257 of trainers.py .
error：“/src/trainers.py", line 265, in update_state
    views = self.view_memory[idx.nonzero().squeeze(dim=1).numpy()]
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)”

Can it be changed to:  “self.view_memory[idx.nonzero().view(-1).numpy()]”  ？

**Comment by KovenYu** [comment]
@123zhen123 Yes if that works in your case. The semantics are quite simple, i.e., using the nonzero indexes.
