### ISSUE TITLE
关于centroids_path； align_path:

### ISSUE THREAD

**Issue by neubb** [KovenYu/state-information#3]
请问如果想直接利用训练好的模型。这两个文件在哪里能找到？而且想问一下这两个文件是与什么 有关的？

**Comment by KovenYu** [comment]
@neubb 直接test的话不需要这两个文件，这俩是training时的初始状态，在第一个iteration时会自动生成.

**Comment by neubb** [comment]
你好，我现在碰到一种情况不知道如何解决。我对你提供的pretrain模型测试，在market数据集上准确率与你提供的数据相似，但是在duke数据集上r1准确率仅有1.6%。r5为3.2%。我对原程序的数据读取方式进行了更改，但确定程序没有问题。请问可能是什么原因导致这种情况呢？
         ` elif 'f' in info[2]:
                #数据集是duke时
                #self.a+=1
                real_tracks.append([info[0], int(info[1][1]), int(info[2][1:-4]), 1])
                #print(info[0])
                view = int(info[1][1]) - 1#摄像头
                Fragment = int(1)
                frames = int(info[2][1:-4])#帧数
                #print(frames)
                camera_cnt = 8
                img = image.load_img(os.path.join(TRAIN, img),target_size=[384, 128])
                img = image.img_to_array(img)#图像
                #cv2.imwrite('/root/data/cunk/DukeMTMC-reID/1.jpg', img)
                #cv2.waitKey(100)
            else:
                # market
                real_tracks.append([info[0], int(info[1][1]), int(info[2]), int(info[1][3])])
                view = int(info[1][1]) - 1#摄像头
                Fragment = int(info[1][3])#片段
                frames = int(info[2])#帧数
                img = image.load_img(os.path.join(TRAIN, img))
                img = image.img_to_array(img)`

**Comment by neubb** [comment]
你好，我现在碰到一些情况不知道如何解决。我在用你提供的pretrained模型对market和duke数据集进行测试，market数据集上表现跟你提供的数据一样，但是在duke数据集上r1数据仅为18.9%,r5为33%。我更改了数据读取方式，我检查了duke数据集读取时的标签，图像，等信息并没有发现错误。请问有什么原因可能导致这种现象吗？
'''
python
        for line in f:
            line = line.strip()
            #去掉开头结尾的空格
            info = line.split('_')
            img = line
            #print(img)
            lbl = line.split('_')[0]
            # 以_为标志将line分开
            if last_label != lbl:
                label_cnt += 1
            last_label = lbl
            #print(label_cnt)
            #统计训练集中标签书量
            #print(img.shape)
            #img = np.transpose(img, (0, 3, 2, 1))
            #img = preprocess_input(img)  # 一个归一化的函数
            #cal_labels =label_cnt
            cal_labels = int(info[0])
            #更改了标签的统计方式
            #似乎没有利用到onehot_label，只用到了cal_label
            #real_tracks.append([info[0], int(info[1][1]), int(info[2]), int(info[1][3])])
            if 'bmp' in info[2]:
                #
                info[2] = info[2].split('.')[0]
            if len(info) > 4 and 'jpe' in info[6]:
                #当数据集是grid的时候
                # grid
                real_tracks.append([info[0], int(info[1][0]), int(info[2]), 1])
            elif 'f' in info[2]:
                #但数据集是duke时
                #self.a+=1
                real_tracks.append([info[0], int(info[1][1]), int(info[2][1:-4]), 1])
                #print(info[0])
                view = int(info[1][1]) - 1#摄像头
                Fragment = int(1)
                frames = int(info[2][1:-4])#帧数
                #print(frames)
                camera_cnt = 8
                img = image.load_img(os.path.join(TRAIN, img),target_size=[384, 128])
                img = image.img_to_array(img)#图像
                #cv2.imwrite('/root/data/cunk/DukeMTMC-reID/1.jpg', img)
                #cv2.waitKey(100)
            else:
                # market
                #print(1)
                real_tracks.append([info[0], int(info[1][1]), int(info[2]), int(info[1][3])])
                view = int(info[1][1]) - 1#摄像头
                Fragment = int(info[1][3])#片段
                frames = int(info[2])#帧数
                img = image.load_img(os.path.join(TRAIN, img))
                img = image.img_to_array(img)
'''
